name: aedificare

on: [push, pull_request]
jobs:
  build_vue:
    runs-on:  ubuntu-latest
    name: aedificare
    steps:
      - uses: actions/checkout
        with:
          fetch-depth: 0
      - uses: actions/setup-node
        with:
          node-version: latest
      - name: inaugurare
          run: npm clean-install
      - name: delere
          if: failure()
          run: exit 1
      - name: fundamen-struere
          run: npm run build
      - name: delere
          if: failure()
          run: exit 1
      - name: verificare
          run: tsc --build --clean
      - name: delere
          if: failure()
          run: exit 1
      - name: structura-struere
          run: npm run type-check
      - name: delere
          if: failure()
          run: exit 1
#      - name: tentare
#          run: npm test --passWithNoTests
#          env:
#            CI: true
#      - name: delere
#         if: failure()
#         run: exit 1
#      - name: invenire
#          run: local locus=$(grep 'outDir' ./tsconfig.json | awk '{ print $2 }') | tr -dc '[:alpha:]\n'
#      - name: emissa
#          run: find ${locus} -type f
#      - name: delere
#          if: failure()
#          run: exit 1
