name: aedificare

on: [ push, pull_request ]
jobs:
  build_vue:
    runs-on:  ubuntu-latest
    name: aedificare
    continue-on-error: false
    stategy:
      fail-fast: true
    steps:
      - uses: actions/checkout
        with:
          fetch-depth: 0
      - uses: actions/setup-node
        with:
          node-version: latest
      - name: inaugurare
        run: npm clean-install
      - name: fundere
        run: npm run type-check
      - name: struere
        run: npm run build
      - name: verificare
        run: tsc --build --clean
#      - name: tentare
#        run: npm test --passWithNoTests
#        env:
#          CI: true
#      - name: invenire
#        run: local locus=$(grep 'outDir' ./tsconfig.json | awk '{ print $2 }') | tr -dc '[:alpha:]\n'
#      - name: emissa
#        run: find ${locus} -type f
