name: aedificare

on:
  workflow_run:
    workflows: [ ESLint ]
    types: [ completed ]
jobs:
  on-success:
    runs-on:  ubuntu-latest
    name: aedificare
    continue-on-error: false
    strategy:
      fail-fast: true
    steps:
      - name: vellere
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: tollere
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
      - name: inaugurare
        run: npm clean-install
      - name: fundere
        run: npm run type-check
      - name: verificare
        run: tsc --build --clean
      - name: struere
        run: npm run build-only
#      - name: tentare
#        run: npm test
#        env:
#          CI: true
      - name: invenire
        run: local locus=$(grep 'outDir' ./tsconfig.json | awk '{ print $2 }') | tr -dc '[:alpha:]\n'
      - name: emissa
        run: local emissa=$(find ${locus} -type f | wc -l)
      - name: delere
        if: ${{ env.emissa }} = 0
        run: |
          printf '::error title=aedificare::defectust'
          exit 1
