name: expedire

on:
  push:
    branches: [ "princeps" ]

jobs:
  call-workflow:
    uses: ./.github/workflows/aedificare.yml
  deploy:
    runs-on:  ubuntu-latest
    name: expedire
    continue-on-error: false
    stategy:
      fail-fast: true
    steps:
      - name: inaugurare
          run: npm install @vue/cli
          continue-on-error: false
#      - name: expedire
#          run: npm run deploy
